apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-tekton-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/RaphaelSve/gitops-demo.git
    path: apps/my-tekton-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-project
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
